/* Generated by AN DISI Unibo */ 
package it.unibo.hold

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Hold ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
		    // Stati slot
		    var FREE = 0
		    var RESERVED = 1
		    var OCCUPIED = 2
		
		    var MAXLOAD = 1000   // imposta dal requisito se diverso
		
		    // 4 slot S1..S4: tre array paralleli
		    var slotState = intArrayOf(FREE, FREE, FREE, FREE)
		    var slotPid   = intArrayOf(0,    0,    0,    0)
		    var slotPeso  = intArrayOf(0,    0,    0,    0)
		
		    fun findFree(): Int {
		      for (i in 0..3) if (slotState[i] == FREE) return i
		      return -1
		    }
		
		    fun reserve(i: Int, pid: Int, peso: Int) {
		      slotState[i] = RESERVED
		      slotPid[i]   = pid
		      slotPeso[i]  = peso
		    }
		
		    fun occupy(i: Int) {
		      if (slotState[i] == RESERVED) slotState[i] = OCCUPIED
		    }
		
		    fun release(i: Int) {
		      slotState[i] = FREE
		      slotPid[i]   = 0
		      slotPeso[i]  = 0
		    }
		
		    fun stateName(v:Int) = when(v){
		      FREE->"FREE"; RESERVED->"RESERVED"; OCCUPIED->"OCCUPIED"; else->"?"
		    }
		
		    fun asString(): String =
		      (0..3).joinToString(" ") { j ->
		        "S${j+1}=${stateName(slotState[j])}(pid=${slotPid[j]},w=${slotPeso[j]})"
		      }
		
		    // Variabili per scambiare dati con le guardie QAK
		    var lastPeso = -1
		    var lastPid  = -1
		    var lastIdx  = -1
		    var invalid  = false
		    var full     = false
		    // (se vuoi aggiungere il controllo di sovrappeso)
		    var overweight = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("hold starting...")
						delay(300) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
				state("ready") { //this:State
					action { //it:State
						CommUtils.outcyan("Hold ready: ${asString()}")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t022",targetState="handleHoldReq",cond=whenRequest("holdrequest"))
				}	 
				state("handleHoldReq") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("holdrequest(PESO,PID)"), Term.createTerm("holdrequest(PESO,PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									        // ---> quando passi ai payload reali, usa invece:
									         lastPeso = payloadArg(0).toInt()
									         lastPid  = payloadArg(1).toInt()
									
									        invalid    = (lastPeso <= 0 || lastPid <= 0)
									        overweight = (lastPeso > MAXLOAD)   
									        lastIdx    = findFree()
									        full       = (lastIdx < 0)
						}
						forward("msg1", "msg1(1)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t123",targetState="invalidPayload",cond=whenDispatchGuarded("msg1",{ invalid  
					}))
					transition(edgeName="t124",targetState="overweight",cond=whenDispatchGuarded("msg1",{ overweight  
					}))
					transition(edgeName="t125",targetState="full",cond=whenDispatchGuarded("msg1",{ full  
					}))
					transition(edgeName="t126",targetState="reserve",cond=whenDispatchGuarded("msg1",{ !invalid && !overweight && !full  
					}))
				}	 
				state("invalidPayload") { //this:State
					action { //it:State
						answer("holdrequest", "holdreplyfailed", "holdreplyfailed(INVALID)"   )  
						CommUtils.outmagenta("INVALID payload (PESO=${lastPeso}, PID=${lastPid})")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
				state("overweight") { //this:State
					action { //it:State
						answer("holdrequest", "holdreplyfailed", "holdreplyfailed(OVERWEIGHT)"   )  
						CommUtils.outmagenta("OVERWEIGHT (PESO=${lastPeso} > MAXLOAD=${MAXLOAD})")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
				state("full") { //this:State
					action { //it:State
						answer("holdrequest", "holdreplyfailed", "holdreplyfailed(FULL)"   )  
						CommUtils.outmagenta("FULL: ${asString()}")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
				state("reserve") { //this:State
					action { //it:State
						
							        reserve(lastIdx, lastPid, lastPeso)
							        var LASTPID = lastPid
							        var SLOTNUMBER = lastIdx + 1
						CommUtils.outmagenta("hold reserved S$SLOTNUMBER for PID=${lastPid} (w=${lastPeso}). State: ${asString()}")
						answer("holdrequest", "holdreply", "holdreply($SLOTNUMBER,$LASTPID)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
			}
		}
} 
