/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
					var ID = 0
					var PESO = 0
					var SLOT = 0
				//REGISTER	 
		 		fun register(){
				
				if( CommUtils.ckeckEureka( ) ){
					val discoveryclient = CommUtils.registerService( main.java.EurekaServiceConfig() )
					CommUtils.outmagenta("discoveryclient=$discoveryclient ")
					CommUtils.outmagenta("EUREKA")
					
				}else{CommUtils.outmagenta("NON VA EUREKA")}
				
				
			}
		
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 sysUtil.logMsgs=true  
						 register()  
						CommUtils.outblack("myself=${myself.name}")
						CommUtils.outblack("curState=${currentState.stateName}")
						CommUtils.outblack("currentMsg=${currentMsg}")
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
				state("waitRequest") { //this:State
					action { //it:State
						delay(500) 
						CommUtils.outblack("Awaiting Requests")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t000",targetState="verifyProductID",cond=whenRequest("requesttoload"))
				}	 
				state("verifyProductID") { //this:State
					action { //it:State
						CommUtils.outblack("Request received - Verifying Product ID...")
						CommUtils.outblack("------------------------------------------")
						if( checkMsgContent( Term.createTerm("requesttoload(PID)"), Term.createTerm("requesttoload(PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												var PID = payloadArg(0).toInt()
												println( PID )
												ID = PID
												CommUtils.outgreen(" PID=$PID ")
						}
						request("productrequest", "productrequest($ID)",createActorDynamically("productpolice", "_p1", false) )
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t121",targetState="waitResponsePolice",cond=whenReply("productreply"))
					transition(edgeName="t122",targetState="requestrefused",cond=whenReply("productreplyfailed"))
				}	 
				state("waitResponsePolice") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("productreply(PESO)"), Term.createTerm("productreply(PESO)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												PESO = payloadArg(0).toInt()
												CommUtils.outgreen(" PESO=$PESO ")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="verifyCargoHold", cond=doswitchGuarded({ PESO!=0  
					}) )
					transition( edgeName="goto",targetState="requestrefused", cond=doswitchGuarded({! ( PESO!=0  
					) }) )
				}	 
				state("verifyCargoHold") { //this:State
					action { //it:State
						CommUtils.outblack("Product Id found in Database - Verifying Cargo Hold Slots Availability and Weight...")
						CommUtils.outblack("------------------------------------------")
						request("holdrequest", "holdrequest($PESO,$ID)" ,"hold" )  
						delay(5000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t113",targetState="handleHoldReply",cond=whenReply("holdreply"))
					transition(edgeName="t114",targetState="requestrefused",cond=whenReply("holdreplyfailed"))
				}	 
				state("handleHoldReply") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("holdreply(SLOT,PID)"), Term.createTerm("holdreply(SLOT,PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												SLOT = payloadArg(0).toInt()
												CommUtils.outblue("CargoService | Slot assegnato=$SLOT")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="verifySonar", cond=doswitchGuarded({ SLOT != 0  
					}) )
					transition( edgeName="goto",targetState="requestrefused", cond=doswitchGuarded({! ( SLOT != 0  
					) }) )
				}	 
				state("verifySonar") { //this:State
					action { //it:State
						CommUtils.outblack("CargoService | Waiting for sonardata to know IOPORT position...")
						request("sonarReq", "sonarReq(X)" ,"sonaradapter" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="move",cond=whenReply("sonarReply"))
					transition(edgeName="t06",targetState="sonarErrorRetry",cond=whenReply("sonarReplyFailure"))
				}	 
				state("sonarErrorRetry") { //this:State
					action { //it:State
						delay(200) 
						CommUtils.outblack("CargoService | SONAR failure -- retrying ")
						request("sonarReq", "sonarReq(X)" ,"sonaradapter" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t17",targetState="move",cond=whenReply("sonarReply"))
					transition(edgeName="t18",targetState="sonarErrorRetry",cond=whenReply("sonarReplyFailure"))
				}	 
				state("move") { //this:State
					action { //it:State
						CommUtils.outblack("CargoService | Engaging robot for delivery...")
						request("moverobotinternal", "moverobot($SLOT)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t19",targetState="deliveryComplete",cond=whenReply("moverobotdone"))
					transition(edgeName="t110",targetState="requestrefused",cond=whenReply("moverobotfailed"))
				}	 
				state("deliveryComplete") { //this:State
					action { //it:State
						CommUtils.outblack("CargoService | Delivery completed successfully!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
				state("requestrefused") { //this:State
					action { //it:State
						CommUtils.outblack("ATTENTION - Request refused")
						CommUtils.outblack("---------------------------")
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
			}
		}
} 
