/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
		        // ========================================================
		        // DEFINIZIONE POJO INLINE: Slot e CargoHold
		        // ========================================================
		        enum class SlotState { FREE, RESERVED }
		
		        class Slot(val id: Int, val targetX: Int, val targetY: Int) {
		            var state: SlotState = SlotState.FREE
		            var pid: Int = 0
		            var peso: Int = 0
		
		            fun reserve(newPid: Int, newPeso: Int) {
		                this.state = SlotState.RESERVED
		                this.pid = newPid
		                this.peso = newPeso
		            }
		            fun release() {
		                this.state = SlotState.FREE
		                this.pid = 0
		                this.peso = 0
		            }
		            override fun toString() = "Slot$id [Stato:$state, PID:$pid, Peso:$peso, Coords:($targetX, $targetY)]"
		        }
		
		        object CargoHoldPojo {
		            private const val MAX_WEIGHT = 1000
		            val slots = listOf(
		                Slot(1, 1, 1),
		                Slot(2, 4, 1),
		                Slot(3, 1, 3),
		                Slot(4, 4, 3)
		            )
		
		            fun reserveSlot(peso: Int, pid: Int): Slot? {
		                if (peso <= 0 || pid <= 0 || peso > MAX_WEIGHT) return null
		                val freeSlot = slots.find { it.state == SlotState.FREE }
		                if (freeSlot != null) {
		                    freeSlot.reserve(pid, peso)
		                    return freeSlot
		                }
		                return null
		            }
		            
		            fun printState() {
		                println("=== STATO CARGOHOLD ===")
		                slots.forEach { println("  - $it") } 
		                println("=======================")
		            }
		        }
		        
		        var ID = 0
		        var PESO = 0
		        var SLOT = 0 // Manterrà l'ID logico per passarlo al robot
		        
		        fun register(){
		            if( CommUtils.ckeckEureka( ) ){
		                val discoveryclient = CommUtils.registerService( main.java.EurekaServiceConfig() )
		                CommUtils.outmagenta("discoveryclient=$discoveryclient ")
		                CommUtils.outmagenta("EUREKA")
		            } else {
		                CommUtils.outmagenta("NON VA EUREKA")
		            }
		        }
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 sysUtil.logMsgs=true  
						 register()  
						CommUtils.outblack("myself=${myself.name}")
						CommUtils.outblack("curState=${currentState.stateName}")
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
				state("waitRequest") { //this:State
					action { //it:State
						delay(500) 
						CommUtils.outblack("Awaiting Requests")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t000",targetState="verifyProductID",cond=whenRequest("requesttoload"))
				}	 
				state("verifyProductID") { //this:State
					action { //it:State
						CommUtils.outblack("Request received - Verifying Product ID...")
						CommUtils.outblack("------------------------------------------")
						if( checkMsgContent( Term.createTerm("requesttoload(PID)"), Term.createTerm("requesttoload(PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												var PID = payloadArg(0).toInt()
												println( PID )
												ID = PID
												CommUtils.outgreen(" PID=$PID ")
						}
						request("productrequest", "productrequest($ID)",createActorDynamically("productpolice", "_p1", false) )
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t121",targetState="waitResponsePolice",cond=whenReply("productreply"))
					transition(edgeName="t122",targetState="requestrefused",cond=whenReply("productreplyfailed"))
				}	 
				state("waitResponsePolice") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("productreply(PESO)"), Term.createTerm("productreply(PESO)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												PESO = payloadArg(0).toInt()
												CommUtils.outgreen(" PESO=$PESO ")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="verifyCargoHold", cond=doswitchGuarded({ PESO!=0  
					}) )
					transition( edgeName="goto",targetState="requestrefused", cond=doswitchGuarded({! ( PESO!=0  
					) }) )
				}	 
				state("verifyCargoHold") { //this:State
					action { //it:State
						CommUtils.outblack("Product Id found in Database - Verifying Cargo Hold Slots Availability and Weight via POJO...")
						CommUtils.outblack("------------------------------------------")
						
						            val assignedSlot = CargoHoldPojo.reserveSlot(PESO, ID)
						            
						            if (assignedSlot != null) {
						                SLOT = assignedSlot.id
						                CommUtils.outblue("CargoService | Slot assegnato = $SLOT")
						                CargoHoldPojo.printState()
						            } else {
						                SLOT = 0
						                CommUtils.outred("CargoService | Errore: Stiva piena, carico non valido o in sovrappeso!")
						            }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="verifySonar", cond=doswitchGuarded({ SLOT != 0  
					}) )
					transition( edgeName="goto",targetState="requestrefused", cond=doswitchGuarded({! ( SLOT != 0  
					) }) )
				}	 
				state("verifySonar") { //this:State
					action { //it:State
						CommUtils.outblack("CargoService | Waiting for sonardata to know IOPORT position...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="move", cond=doswitch() )
				}	 
				state("move") { //this:State
					action { //it:State
						CommUtils.outblack("CargoService | Engaging robot for delivery to SLOT $SLOT...")
						request("moverobotinternal", "moverobotinternal($SLOT)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t13",targetState="deliveryComplete",cond=whenReply("moverobotinternaldone"))
					transition(edgeName="t14",targetState="requestrefused",cond=whenReply("moverobotinternalfailed"))
				}	 
				state("deliveryComplete") { //this:State
					action { //it:State
						CommUtils.outblack("CargoService | Delivery completed successfully!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
				state("requestrefused") { //this:State
					action { //it:State
						CommUtils.outblack("ATTENTION - Request refused")
						CommUtils.outblack("---------------------------")
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
			}
		}
} 
