/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 
		        var TARGETX = 0
		        var TARGETY = 0
		        var SLOT = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("CargoRobot ready and waiting for movement requests...")
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
				state("waitRequest") { //this:State
					action { //it:State
						CommUtils.outblack("CargoRobot | Waiting for load request...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t013",targetState="engage",cond=whenRequest("moverobotinternal"))
				}	 
				state("engage") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobot(SLOT)"), Term.createTerm("moverobot(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								            	CommUtils.outblue("-------- Received request with SLOT ---------")
								                var slot = payloadArg(0).toInt()
								                println( slot ) 
								                var coords = when(slot) {
								                    1 -> Pair(1, 1)
								                    2 -> Pair(4, 1)
								                    3 -> Pair(1, 3)
								                    4 -> Pair(4, 3)
								                    else -> Pair(0, 0)
								                }
								                TARGETX = coords.first
								                TARGETY = coords.second
								                CommUtils.outblue("CargoRobot | Slot=$slot -> coords=($TARGETX,$TARGETY)")
								request("engage", "engage($MyName,330)" ,"basicrobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t114",targetState="goToIOPort",cond=whenReply("engagedone"))
					transition(edgeName="t115",targetState="refused",cond=whenReply("engagerefused"))
				}	 
				state("goToIOPort") { //this:State
					action { //it:State
						delay(500) 
						CommUtils.outblack("CargoRobot | Moving to IOPORT to pick up cargo...")
						request("moverobot", "moverobot(0,4)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t216",targetState="goToTarget",cond=whenReply("moverobotdone"))
					transition(edgeName="t217",targetState="refused",cond=whenReply("moverobotfailed"))
				}	 
				state("goToTarget") { //this:State
					action { //it:State
						delay(2000) 
						
						        	CommUtils.outblue("CargoRobot | Delivering cargo to ($TARGETX,$TARGETY)")
						request("moverobot", "moverobot($TARGETX,$TARGETY)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t318",targetState="goHome",cond=whenReply("moverobotdone"))
					transition(edgeName="t319",targetState="refused",cond=whenReply("moverobotfailed"))
				}	 
				state("goHome") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outblack("CargoRobot | Returning to base...")
						request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t420",targetState="done",cond=whenReply("moverobotdone"))
					transition(edgeName="t421",targetState="refused",cond=whenReply("moverobotfailed"))
				}	 
				state("done") { //this:State
					action { //it:State
						forward("disengage", "disengage(ok)" ,"basicrobot" ) 
						CommUtils.outblack("CargoRobot | Delivery completed.")
						answer("moverobot", "moverobotdone", "moverobotok(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("refused") { //this:State
					action { //it:State
						CommUtils.outblack("CargoRobot | Movement failed.")
						answer("moverobot", "moverobotfailed", "moverobotfailed(no,no)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
} 
