/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 
		        var TARGETX = 0
		        var TARGETY = 0
		        var SLOT = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("CargoRobot ready and waiting for movement requests...")
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
				state("waitRequest") { //this:State
					action { //it:State
						CommUtils.outblack("CargoRobot | Waiting for load request...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="engage",cond=whenRequest("moverobotinternal"))
				}	 
				state("engage") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobotinternal(SLOT)"), Term.createTerm("moverobotinternal(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                CommUtils.outblue("-------- Received request with SLOT ---------")
								                var slotId = payloadArg(0).toInt()
								                
								                // Recuperiamo le coordinate dall'oggetto Slot
								                val mySlot = cargoservice.CargoHoldPojo.slots.find { it.id == slotId }
								                
								                if (mySlot != null) {
								                    TARGETX = mySlot.targetX
								                    TARGETY = mySlot.targetY
								                } else {
								                    TARGETX = 0
								                    TARGETY = 0
								                }
								                
								                CommUtils.outblue("CargoRobot | Slot=$slotId -> coords=($TARGETX,$TARGETY)")
								request("engage", "engage($MyName,330)" ,"basicrobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t18",targetState="goToIOPort",cond=whenReply("engagedone"))
					transition(edgeName="t19",targetState="refused",cond=whenReply("engagerefused"))
				}	 
				state("goToIOPort") { //this:State
					action { //it:State
						delay(500) 
						CommUtils.outblack("CargoRobot | Moving to IOPORT to pick up cargo...")
						request("moverobot", "moverobot(0,4)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t210",targetState="goToTarget",cond=whenReply("moverobotdone"))
					transition(edgeName="t211",targetState="refused",cond=whenReply("moverobotfailed"))
				}	 
				state("goToTarget") { //this:State
					action { //it:State
						delay(2000) 
						 CommUtils.outblue("CargoRobot | Delivering cargo to ($TARGETX,$TARGETY)")  
						request("moverobot", "moverobot($TARGETX,$TARGETY)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t312",targetState="goHome",cond=whenReply("moverobotdone"))
					transition(edgeName="t313",targetState="refused",cond=whenReply("moverobotfailed"))
				}	 
				state("goHome") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outblack("CargoRobot | Returning to base...")
						request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t414",targetState="done",cond=whenReply("moverobotdone"))
					transition(edgeName="t415",targetState="refused",cond=whenReply("moverobotfailed"))
				}	 
				state("done") { //this:State
					action { //it:State
						forward("disengage", "disengage(ok)" ,"basicrobot" ) 
						CommUtils.outblack("CargoRobot | Delivery completed.")
						answer("moverobotinternal", "moverobotinternaldone", "moverobotinternalok(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("refused") { //this:State
					action { //it:State
						CommUtils.outblack("CargoRobot | Movement failed.")
						answer("moverobotinternal", "moverobotinternalfailed", "moverobotinternalfailed(no,no)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
} 
