/* Generated by AN DISI Unibo */ 
package it.unibo.sonaradapter

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonaradapter ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
					var D = 0 
					var DFREE = 10
					var GUASTO = false 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(200) 
						CommUtils.outmagenta("--------- sonaradapter ACTOR ONLINE -----------")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="awaitingRequest", cond=doswitch() )
				}	 
				state("awaitingRequest") { //this:State
					action { //it:State
						CommUtils.outmagenta("--------- Waiting a Request -----------")
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("--------- Printing Sonar Data -----------")
								  D = payloadArg(0).toInt()  
								CommUtils.outmagenta("$name | handleSonardata D=$D DFREE=$DFREE")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t027",targetState="handleRequest",cond=whenRequest("sonarReq"))
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonarReq(X)"), Term.createTerm("sonarReq(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("---------SONAR REQUEST RECEIVED -------")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t128",targetState="handleSonarData",cond=whenEvent("sonardata"))
				}	 
				state("handleSonarData") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  D = payloadArg(0).toInt()  
								CommUtils.outmagenta("$name | handleSonardata D=$D DFREE=$DFREE")
								if(  D > DFREE   
								 ){CommUtils.outmagenta("from SONAR | ledON | FAILURE")
								 GUASTO = true  
								}
								if(  D <= DFREE/2   
								 ){CommUtils.outmagenta("from SONAR | ledOFF | PRODOTTO TROVATO")
								 GUASTO = false  
								}
						}
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t229",targetState="verifyData",cond=whenEvent("sonardata"))
				}	 
				state("verifyData") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  D = payloadArg(0).toInt()  
								CommUtils.outcyan("$name | handleSonardata D=$D DFREE=$DFREE")
								if(  D > DFREE   
								 ){CommUtils.outmagenta("from SONAR | ledON | FAILURE")
								 GUASTO = true  
								}
								if(  D <= DFREE/2   
								 ){CommUtils.outmagenta("from SONAR | ledOFF | PRODOTTO TROVATO")
								 GUASTO = false  
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="productAtIOPort", cond=doswitchGuarded({ !GUASTO  
					}) )
					transition( edgeName="goto",targetState="handleFailure", cond=doswitchGuarded({! ( !GUASTO  
					) }) )
				}	 
				state("productAtIOPort") { //this:State
					action { //it:State
						answer("sonarReq", "sonarReply", "sonarReply(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="awaitingRequest", cond=doswitch() )
				}	 
				state("handleFailure") { //this:State
					action { //it:State
						answer("sonarReq", "sonarReplyFailure", "sonarReplyFailure(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="awaitingRequest", cond=doswitch() )
				}	 
			}
		}
} 
