# URL del server Eureka  USATO PER REGISRARE
eureka.serviceUrl.defaultZone= http://localhost:8761/, http://eureka:8761/eureka/, http://172.19.103.74:8761/eureka/ ,http://192.168.1.10:8761/eureka/
 # Porta del servizio
 eureka.instance.appname=ctxusermock
 eureka.instance.port=8887
# eureka.instance.ipAddress= 10.152.235.74
# Intervallo di rinnovo del lease (cuore pulsante)
eureka.leaseRenewalIntervalInSeconds=60
eureka.instance.prefer-ip-address=true
# Intervallo di espirazione del lease
eureka.leaseExpirationDurationInSeconds=60