/* Generated by AN DISI Unibo */ 
package it.unibo.user

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class User ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				lateinit var eurekaClient : com.netflix.discovery.DiscoveryClient 
		
		//REGISTER	 
		 fun register(){
				
				if( CommUtils.ckeckEureka( ) ){
					val discoveryclient = CommUtils.registerService( main.java.EurekaServiceConfig() )
					CommUtils.outmagenta("discoveryclient=$discoveryclient ")
					CommUtils.outmagenta("EUREKA")
					
				}else{CommUtils.outmagenta("NON VA EUREKA")}	 
		}
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 register()  
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s1", cond=doswitch() )
				}	 
				state("s1") { //this:State
					action { //it:State
						CommUtils.outblack("SEND REQUEST PID: 17")
						request("requesttoload", "requesttoload(17)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait1", cond=doswitch() )
				}	 
				state("wait1") { //this:State
					action { //it:State
						delay(10000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s2", cond=doswitch() )
				}	 
				state("s2") { //this:State
					action { //it:State
						CommUtils.outblack("SEND REQUEST PID: 3")
						request("requesttoload", "requesttoload(3)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait2", cond=doswitch() )
				}	 
				state("wait2") { //this:State
					action { //it:State
						delay(10000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s3", cond=doswitch() )
				}	 
				state("s3") { //this:State
					action { //it:State
						CommUtils.outblack("SEND REQUEST PID: 8")
						request("requesttoload", "requesttoload(8)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait3", cond=doswitch() )
				}	 
				state("wait3") { //this:State
					action { //it:State
						delay(10000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s4", cond=doswitch() )
				}	 
				state("s4") { //this:State
					action { //it:State
						CommUtils.outblack("SEND REQUEST PID: 9")
						request("requesttoload", "requesttoload(9)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait4", cond=doswitch() )
				}	 
				state("wait4") { //this:State
					action { //it:State
						delay(10000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s5", cond=doswitch() )
				}	 
				state("s5") { //this:State
					action { //it:State
						CommUtils.outblack("SEND REQUEST PID: 9")
						request("requesttoload", "requesttoload(9)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="end", cond=doswitch() )
				}	 
				state("end") { //this:State
					action { //it:State
						delay(10000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="end", cond=doswitch() )
				}	 
			}
		}
} 
